message-remove-the-hat: §cIt is impossible to put on a banner, first take off your hat
message-done: §aDone! You can remove the banner from the inventory
message-take-flag-in-hand: §cFirst, take the flag in your hand!